global:
  scrape_interval: 15s
  evaluation_interval: 15s
  scrape_timeout: 10s
  external_labels:
    stack: n8n

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: prometheus

  - job_name: traefik
    metrics_path: /metrics
    static_configs:
      - targets: ['traefik:8081']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: traefik

  - job_name: n8n_main
    metrics_path: /metrics
    static_configs:
      - targets:
      - 'main:5678'
      - 'runner-main:5678'
      - 'worker:5678'
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: n8n-main

  # Queue mode only (will be DOWN in single mode if service doesn't exist)
  - job_name: n8n_worker
    metrics_path: /metrics
    static_configs:
      - targets: ['worker:5678']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: n8n-worker

  - job_name: postgres_exporter
    static_configs:
      - targets: ['postgres-exporter:9187']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: postgres

  # Queue mode only (will be DOWN in single mode if service doesn't exist)
  - job_name: redis_exporter
    static_configs:
      - targets: ['redis-exporter:9121']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: redis

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: cadvisor

  - job_name: node-exporter
    static_configs:
      - targets: ['node-exporter:9100']
    relabel_configs:
      - source_labels: [__address__]
        target_label: instance
        replacement: node
