global:
  scrape_interval: 15s
  evaluation_interval: 15s

scrape_configs:
  - job_name: prometheus
    static_configs:
      - targets: ['prometheus:9090']

  - job_name: traefik
    metrics_path: /metrics
    static_configs:
      - targets: ['traefik:8081']

  - job_name: n8n
    metrics_path: /metrics
    static_configs:
      - targets: ['main:5678']

  - job_name: postgres_exporter
    static_configs:
      - targets: ['postgres-exporter:9187']

  - job_name: redis_exporter
    static_configs:
      - targets: ['redis-exporter:9121']

  - job_name: cadvisor
    static_configs:
      - targets: ['cadvisor:8080']

  - job_name: node-exporter
    static_configs:
      - targets: ['143.198.194.212:9100']

